website:
    title: "faraonelab.github.io/protocols"
    site-url: https://faraonelab.github.io/protocols/
    navbar:
      left:
        - href: index.qmd
          text: Home
        - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual