on:
  push:
    branches: [ main ] # Only deploy to live site when pushed to main

name: Quarto Publish Encrypted

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install R & Dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Install Staticrypt
        run: npm install -g staticrypt

      - name: Render and Encrypt
        run: |
          quarto render
          staticrypt docs -r -o docs --short --password "${{ secrets.SITE_PASSWORD }}"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true